use_frameworks!

target 'RxStore_Example' do
  pod 'Dip'
  pod 'RxStore', :path => '../'

  target 'RxStore_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0'
    pod 'Nimble', '~> 7.3.4'
  end
end
